// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// This file was modified from its original version for inclusion in parquet-cpp.
// Original source:
// https://github.com/lemire/FrameOfReference/blob/6ccaf9e97160f9a3b299e23a8ef739e711ef0c71/src/bpacking.cpp
// The original copyright notice follows.

// This code is released under the
// Apache License Version 2.0 http://www.apache.org/licenses/.
// (c) Daniel Lemire 2013

#pragma once

#include <type_traits>
#include <cassert>
#include <cstring>

#if defined(__AVX512F__)
#include <immintrin.h>
#endif

namespace parquet4seastar {

namespace util {
template <typename T>
inline typename std::enable_if_t<std::is_trivial<T>::value, T> SafeLoad(const T* unaligned) {
  std::remove_const_t<T> ret;
  std::memcpy(&ret, unaligned, sizeof(T));
  return ret;
}
}

namespace internal {

#if defined(__AVX512F__)
inline const uint32_t* unpack1_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  __m512i shifts, inls, masks, result;

  inls = _mm512_set1_epi32(inl);
  masks = _mm512_set1_epi32(1);

  // shift the first 16 outs
  shifts = _mm512_set_epi32(15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0);
  result = _mm512_and_epi32(_mm512_srlv_epi32(inls, shifts), masks);
  memcpy(out, &result, 16 * sizeof(*out));
  out += 16;

  // shift the last 16 outs
  shifts =
      _mm512_set_epi32(31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16);
  result = _mm512_and_epi32(_mm512_srlv_epi32(inls, shifts), masks);
  memcpy(out, &result, 16 * sizeof(*out));
  out += 16;

  ++in;

  return in;
}
#else
inline const uint32_t* unpack1_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 1;
  out++;
  *out = (inl >> 1) & 1;
  out++;
  *out = (inl >> 2) & 1;
  out++;
  *out = (inl >> 3) & 1;
  out++;
  *out = (inl >> 4) & 1;
  out++;
  *out = (inl >> 5) & 1;
  out++;
  *out = (inl >> 6) & 1;
  out++;
  *out = (inl >> 7) & 1;
  out++;
  *out = (inl >> 8) & 1;
  out++;
  *out = (inl >> 9) & 1;
  out++;
  *out = (inl >> 10) & 1;
  out++;
  *out = (inl >> 11) & 1;
  out++;
  *out = (inl >> 12) & 1;
  out++;
  *out = (inl >> 13) & 1;
  out++;
  *out = (inl >> 14) & 1;
  out++;
  *out = (inl >> 15) & 1;
  out++;
  *out = (inl >> 16) & 1;
  out++;
  *out = (inl >> 17) & 1;
  out++;
  *out = (inl >> 18) & 1;
  out++;
  *out = (inl >> 19) & 1;
  out++;
  *out = (inl >> 20) & 1;
  out++;
  *out = (inl >> 21) & 1;
  out++;
  *out = (inl >> 22) & 1;
  out++;
  *out = (inl >> 23) & 1;
  out++;
  *out = (inl >> 24) & 1;
  out++;
  *out = (inl >> 25) & 1;
  out++;
  *out = (inl >> 26) & 1;
  out++;
  *out = (inl >> 27) & 1;
  out++;
  *out = (inl >> 28) & 1;
  out++;
  *out = (inl >> 29) & 1;
  out++;
  *out = (inl >> 30) & 1;
  out++;
  *out = (inl >> 31);
  ++in;
  out++;

  return in;
}
#endif

inline const uint32_t* unpack2_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x3;
  out++;
  *out = (inl >> 2) & 0x3;
  out++;
  *out = (inl >> 4) & 0x3;
  out++;
  *out = (inl >> 6) & 0x3;
  out++;
  *out = (inl >> 8) & 0x3;
  out++;
  *out = (inl >> 10) & 0x3;
  out++;
  *out = (inl >> 12) & 0x3;
  out++;
  *out = (inl >> 14) & 0x3;
  out++;
  *out = (inl >> 16) & 0x3;
  out++;
  *out = (inl >> 18) & 0x3;
  out++;
  *out = (inl >> 20) & 0x3;
  out++;
  *out = (inl >> 22) & 0x3;
  out++;
  *out = (inl >> 24) & 0x3;
  out++;
  *out = (inl >> 26) & 0x3;
  out++;
  *out = (inl >> 28) & 0x3;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0x3;
  out++;
  *out = (inl >> 2) & 0x3;
  out++;
  *out = (inl >> 4) & 0x3;
  out++;
  *out = (inl >> 6) & 0x3;
  out++;
  *out = (inl >> 8) & 0x3;
  out++;
  *out = (inl >> 10) & 0x3;
  out++;
  *out = (inl >> 12) & 0x3;
  out++;
  *out = (inl >> 14) & 0x3;
  out++;
  *out = (inl >> 16) & 0x3;
  out++;
  *out = (inl >> 18) & 0x3;
  out++;
  *out = (inl >> 20) & 0x3;
  out++;
  *out = (inl >> 22) & 0x3;
  out++;
  *out = (inl >> 24) & 0x3;
  out++;
  *out = (inl >> 26) & 0x3;
  out++;
  *out = (inl >> 28) & 0x3;
  out++;
  *out = (inl >> 30);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack3_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x7;
  out++;
  *out = (inl >> 3) & 0x7;
  out++;
  *out = (inl >> 6) & 0x7;
  out++;
  *out = (inl >> 9) & 0x7;
  out++;
  *out = (inl >> 12) & 0x7;
  out++;
  *out = (inl >> 15) & 0x7;
  out++;
  *out = (inl >> 18) & 0x7;
  out++;
  *out = (inl >> 21) & 0x7;
  out++;
  *out = (inl >> 24) & 0x7;
  out++;
  *out = (inl >> 27) & 0x7;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl % (1U << 1)) << (3 - 1);
  out++;
  *out = (inl >> 1) & 0x7;
  out++;
  *out = (inl >> 4) & 0x7;
  out++;
  *out = (inl >> 7) & 0x7;
  out++;
  *out = (inl >> 10) & 0x7;
  out++;
  *out = (inl >> 13) & 0x7;
  out++;
  *out = (inl >> 16) & 0x7;
  out++;
  *out = (inl >> 19) & 0x7;
  out++;
  *out = (inl >> 22) & 0x7;
  out++;
  *out = (inl >> 25) & 0x7;
  out++;
  *out = (inl >> 28) & 0x7;
  out++;
  *out = (inl >> 31);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (3 - 2);
  out++;
  *out = (inl >> 2) & 0x7;
  out++;
  *out = (inl >> 5) & 0x7;
  out++;
  *out = (inl >> 8) & 0x7;
  out++;
  *out = (inl >> 11) & 0x7;
  out++;
  *out = (inl >> 14) & 0x7;
  out++;
  *out = (inl >> 17) & 0x7;
  out++;
  *out = (inl >> 20) & 0x7;
  out++;
  *out = (inl >> 23) & 0x7;
  out++;
  *out = (inl >> 26) & 0x7;
  out++;
  *out = (inl >> 29);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack4_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0xF;
  out++;
  *out = (inl >> 4) & 0xF;
  out++;
  *out = (inl >> 8) & 0xF;
  out++;
  *out = (inl >> 12) & 0xF;
  out++;
  *out = (inl >> 16) & 0xF;
  out++;
  *out = (inl >> 20) & 0xF;
  out++;
  *out = (inl >> 24) & 0xF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xF;
  out++;
  *out = (inl >> 4) & 0xF;
  out++;
  *out = (inl >> 8) & 0xF;
  out++;
  *out = (inl >> 12) & 0xF;
  out++;
  *out = (inl >> 16) & 0xF;
  out++;
  *out = (inl >> 20) & 0xF;
  out++;
  *out = (inl >> 24) & 0xF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xF;
  out++;
  *out = (inl >> 4) & 0xF;
  out++;
  *out = (inl >> 8) & 0xF;
  out++;
  *out = (inl >> 12) & 0xF;
  out++;
  *out = (inl >> 16) & 0xF;
  out++;
  *out = (inl >> 20) & 0xF;
  out++;
  *out = (inl >> 24) & 0xF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xF;
  out++;
  *out = (inl >> 4) & 0xF;
  out++;
  *out = (inl >> 8) & 0xF;
  out++;
  *out = (inl >> 12) & 0xF;
  out++;
  *out = (inl >> 16) & 0xF;
  out++;
  *out = (inl >> 20) & 0xF;
  out++;
  *out = (inl >> 24) & 0xF;
  out++;
  *out = (inl >> 28);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack5_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x1F;
  out++;
  *out = (inl >> 5) & 0x1F;
  out++;
  *out = (inl >> 10) & 0x1F;
  out++;
  *out = (inl >> 15) & 0x1F;
  out++;
  *out = (inl >> 20) & 0x1F;
  out++;
  *out = (inl >> 25) & 0x1F;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7) << (5 - 3);
  out++;
  *out = (inl >> 3) & 0x1F;
  out++;
  *out = (inl >> 8) & 0x1F;
  out++;
  *out = (inl >> 13) & 0x1F;
  out++;
  *out = (inl >> 18) & 0x1F;
  out++;
  *out = (inl >> 23) & 0x1F;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl % (1U << 1)) << (5 - 1);
  out++;
  *out = (inl >> 1) & 0x1F;
  out++;
  *out = (inl >> 6) & 0x1F;
  out++;
  *out = (inl >> 11) & 0x1F;
  out++;
  *out = (inl >> 16) & 0x1F;
  out++;
  *out = (inl >> 21) & 0x1F;
  out++;
  *out = (inl >> 26) & 0x1F;
  out++;
  *out = (inl >> 31);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (5 - 4);
  out++;
  *out = (inl >> 4) & 0x1F;
  out++;
  *out = (inl >> 9) & 0x1F;
  out++;
  *out = (inl >> 14) & 0x1F;
  out++;
  *out = (inl >> 19) & 0x1F;
  out++;
  *out = (inl >> 24) & 0x1F;
  out++;
  *out = (inl >> 29);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (5 - 2);
  out++;
  *out = (inl >> 2) & 0x1F;
  out++;
  *out = (inl >> 7) & 0x1F;
  out++;
  *out = (inl >> 12) & 0x1F;
  out++;
  *out = (inl >> 17) & 0x1F;
  out++;
  *out = (inl >> 22) & 0x1F;
  out++;
  *out = (inl >> 27);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack6_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x3F;
  out++;
  *out = (inl >> 6) & 0x3F;
  out++;
  *out = (inl >> 12) & 0x3F;
  out++;
  *out = (inl >> 18) & 0x3F;
  out++;
  *out = (inl >> 24) & 0x3F;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (6 - 4);
  out++;
  *out = (inl >> 4) & 0x3F;
  out++;
  *out = (inl >> 10) & 0x3F;
  out++;
  *out = (inl >> 16) & 0x3F;
  out++;
  *out = (inl >> 22) & 0x3F;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (6 - 2);
  out++;
  *out = (inl >> 2) & 0x3F;
  out++;
  *out = (inl >> 8) & 0x3F;
  out++;
  *out = (inl >> 14) & 0x3F;
  out++;
  *out = (inl >> 20) & 0x3F;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0x3F;
  out++;
  *out = (inl >> 6) & 0x3F;
  out++;
  *out = (inl >> 12) & 0x3F;
  out++;
  *out = (inl >> 18) & 0x3F;
  out++;
  *out = (inl >> 24) & 0x3F;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (6 - 4);
  out++;
  *out = (inl >> 4) & 0x3F;
  out++;
  *out = (inl >> 10) & 0x3F;
  out++;
  *out = (inl >> 16) & 0x3F;
  out++;
  *out = (inl >> 22) & 0x3F;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (6 - 2);
  out++;
  *out = (inl >> 2) & 0x3F;
  out++;
  *out = (inl >> 8) & 0x3F;
  out++;
  *out = (inl >> 14) & 0x3F;
  out++;
  *out = (inl >> 20) & 0x3F;
  out++;
  *out = (inl >> 26);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack7_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x7F;
  out++;
  *out = (inl >> 7) & 0x7F;
  out++;
  *out = (inl >> 14) & 0x7F;
  out++;
  *out = (inl >> 21) & 0x7F;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7) << (7 - 3);
  out++;
  *out = (inl >> 3) & 0x7F;
  out++;
  *out = (inl >> 10) & 0x7F;
  out++;
  *out = (inl >> 17) & 0x7F;
  out++;
  *out = (inl >> 24) & 0x7F;
  out++;
  *out = (inl >> 31);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (7 - 6);
  out++;
  *out = (inl >> 6) & 0x7F;
  out++;
  *out = (inl >> 13) & 0x7F;
  out++;
  *out = (inl >> 20) & 0x7F;
  out++;
  *out = (inl >> 27);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (7 - 2);
  out++;
  *out = (inl >> 2) & 0x7F;
  out++;
  *out = (inl >> 9) & 0x7F;
  out++;
  *out = (inl >> 16) & 0x7F;
  out++;
  *out = (inl >> 23) & 0x7F;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1F) << (7 - 5);
  out++;
  *out = (inl >> 5) & 0x7F;
  out++;
  *out = (inl >> 12) & 0x7F;
  out++;
  *out = (inl >> 19) & 0x7F;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl % (1U << 1)) << (7 - 1);
  out++;
  *out = (inl >> 1) & 0x7F;
  out++;
  *out = (inl >> 8) & 0x7F;
  out++;
  *out = (inl >> 15) & 0x7F;
  out++;
  *out = (inl >> 22) & 0x7F;
  out++;
  *out = (inl >> 29);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (7 - 4);
  out++;
  *out = (inl >> 4) & 0x7F;
  out++;
  *out = (inl >> 11) & 0x7F;
  out++;
  *out = (inl >> 18) & 0x7F;
  out++;
  *out = (inl >> 25);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack8_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0xFF;
  out++;
  *out = (inl >> 8) & 0xFF;
  out++;
  *out = (inl >> 16) & 0xFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFF;
  out++;
  *out = (inl >> 8) & 0xFF;
  out++;
  *out = (inl >> 16) & 0xFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFF;
  out++;
  *out = (inl >> 8) & 0xFF;
  out++;
  *out = (inl >> 16) & 0xFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFF;
  out++;
  *out = (inl >> 8) & 0xFF;
  out++;
  *out = (inl >> 16) & 0xFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFF;
  out++;
  *out = (inl >> 8) & 0xFF;
  out++;
  *out = (inl >> 16) & 0xFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFF;
  out++;
  *out = (inl >> 8) & 0xFF;
  out++;
  *out = (inl >> 16) & 0xFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFF;
  out++;
  *out = (inl >> 8) & 0xFF;
  out++;
  *out = (inl >> 16) & 0xFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFF;
  out++;
  *out = (inl >> 8) & 0xFF;
  out++;
  *out = (inl >> 16) & 0xFF;
  out++;
  *out = (inl >> 24);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack9_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x1FF;
  out++;
  *out = (inl >> 9) & 0x1FF;
  out++;
  *out = (inl >> 18) & 0x1FF;
  out++;
  *out = (inl >> 27);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (9 - 4);
  out++;
  *out = (inl >> 4) & 0x1FF;
  out++;
  *out = (inl >> 13) & 0x1FF;
  out++;
  *out = (inl >> 22) & 0x1FF;
  out++;
  *out = (inl >> 31);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (9 - 8);
  out++;
  *out = (inl >> 8) & 0x1FF;
  out++;
  *out = (inl >> 17) & 0x1FF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7) << (9 - 3);
  out++;
  *out = (inl >> 3) & 0x1FF;
  out++;
  *out = (inl >> 12) & 0x1FF;
  out++;
  *out = (inl >> 21) & 0x1FF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7F) << (9 - 7);
  out++;
  *out = (inl >> 7) & 0x1FF;
  out++;
  *out = (inl >> 16) & 0x1FF;
  out++;
  *out = (inl >> 25);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (9 - 2);
  out++;
  *out = (inl >> 2) & 0x1FF;
  out++;
  *out = (inl >> 11) & 0x1FF;
  out++;
  *out = (inl >> 20) & 0x1FF;
  out++;
  *out = (inl >> 29);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (9 - 6);
  out++;
  *out = (inl >> 6) & 0x1FF;
  out++;
  *out = (inl >> 15) & 0x1FF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl % (1U << 1)) << (9 - 1);
  out++;
  *out = (inl >> 1) & 0x1FF;
  out++;
  *out = (inl >> 10) & 0x1FF;
  out++;
  *out = (inl >> 19) & 0x1FF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1F) << (9 - 5);
  out++;
  *out = (inl >> 5) & 0x1FF;
  out++;
  *out = (inl >> 14) & 0x1FF;
  out++;
  *out = (inl >> 23);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack10_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x3FF;
  out++;
  *out = (inl >> 10) & 0x3FF;
  out++;
  *out = (inl >> 20) & 0x3FF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (10 - 8);
  out++;
  *out = (inl >> 8) & 0x3FF;
  out++;
  *out = (inl >> 18) & 0x3FF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (10 - 6);
  out++;
  *out = (inl >> 6) & 0x3FF;
  out++;
  *out = (inl >> 16) & 0x3FF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (10 - 4);
  out++;
  *out = (inl >> 4) & 0x3FF;
  out++;
  *out = (inl >> 14) & 0x3FF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (10 - 2);
  out++;
  *out = (inl >> 2) & 0x3FF;
  out++;
  *out = (inl >> 12) & 0x3FF;
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0x3FF;
  out++;
  *out = (inl >> 10) & 0x3FF;
  out++;
  *out = (inl >> 20) & 0x3FF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (10 - 8);
  out++;
  *out = (inl >> 8) & 0x3FF;
  out++;
  *out = (inl >> 18) & 0x3FF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (10 - 6);
  out++;
  *out = (inl >> 6) & 0x3FF;
  out++;
  *out = (inl >> 16) & 0x3FF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (10 - 4);
  out++;
  *out = (inl >> 4) & 0x3FF;
  out++;
  *out = (inl >> 14) & 0x3FF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (10 - 2);
  out++;
  *out = (inl >> 2) & 0x3FF;
  out++;
  *out = (inl >> 12) & 0x3FF;
  out++;
  *out = (inl >> 22);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack11_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x7FF;
  out++;
  *out = (inl >> 11) & 0x7FF;
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl % (1U << 1)) << (11 - 1);
  out++;
  *out = (inl >> 1) & 0x7FF;
  out++;
  *out = (inl >> 12) & 0x7FF;
  out++;
  *out = (inl >> 23);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (11 - 2);
  out++;
  *out = (inl >> 2) & 0x7FF;
  out++;
  *out = (inl >> 13) & 0x7FF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7) << (11 - 3);
  out++;
  *out = (inl >> 3) & 0x7FF;
  out++;
  *out = (inl >> 14) & 0x7FF;
  out++;
  *out = (inl >> 25);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (11 - 4);
  out++;
  *out = (inl >> 4) & 0x7FF;
  out++;
  *out = (inl >> 15) & 0x7FF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1F) << (11 - 5);
  out++;
  *out = (inl >> 5) & 0x7FF;
  out++;
  *out = (inl >> 16) & 0x7FF;
  out++;
  *out = (inl >> 27);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (11 - 6);
  out++;
  *out = (inl >> 6) & 0x7FF;
  out++;
  *out = (inl >> 17) & 0x7FF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7F) << (11 - 7);
  out++;
  *out = (inl >> 7) & 0x7FF;
  out++;
  *out = (inl >> 18) & 0x7FF;
  out++;
  *out = (inl >> 29);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (11 - 8);
  out++;
  *out = (inl >> 8) & 0x7FF;
  out++;
  *out = (inl >> 19) & 0x7FF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FF) << (11 - 9);
  out++;
  *out = (inl >> 9) & 0x7FF;
  out++;
  *out = (inl >> 20) & 0x7FF;
  out++;
  *out = (inl >> 31);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (11 - 10);
  out++;
  *out = (inl >> 10) & 0x7FF;
  out++;
  *out = (inl >> 21);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack12_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0xFFF;
  out++;
  *out = (inl >> 12) & 0xFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (12 - 4);
  out++;
  *out = (inl >> 4) & 0xFFF;
  out++;
  *out = (inl >> 16) & 0xFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (12 - 8);
  out++;
  *out = (inl >> 8) & 0xFFF;
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFF;
  out++;
  *out = (inl >> 12) & 0xFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (12 - 4);
  out++;
  *out = (inl >> 4) & 0xFFF;
  out++;
  *out = (inl >> 16) & 0xFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (12 - 8);
  out++;
  *out = (inl >> 8) & 0xFFF;
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFF;
  out++;
  *out = (inl >> 12) & 0xFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (12 - 4);
  out++;
  *out = (inl >> 4) & 0xFFF;
  out++;
  *out = (inl >> 16) & 0xFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (12 - 8);
  out++;
  *out = (inl >> 8) & 0xFFF;
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFF;
  out++;
  *out = (inl >> 12) & 0xFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (12 - 4);
  out++;
  *out = (inl >> 4) & 0xFFF;
  out++;
  *out = (inl >> 16) & 0xFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (12 - 8);
  out++;
  *out = (inl >> 8) & 0xFFF;
  out++;
  *out = (inl >> 20);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack13_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x1FFF;
  out++;
  *out = (inl >> 13) & 0x1FFF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7F) << (13 - 7);
  out++;
  *out = (inl >> 7) & 0x1FFF;
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl % (1U << 1)) << (13 - 1);
  out++;
  *out = (inl >> 1) & 0x1FFF;
  out++;
  *out = (inl >> 14) & 0x1FFF;
  out++;
  *out = (inl >> 27);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (13 - 8);
  out++;
  *out = (inl >> 8) & 0x1FFF;
  out++;
  *out = (inl >> 21);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (13 - 2);
  out++;
  *out = (inl >> 2) & 0x1FFF;
  out++;
  *out = (inl >> 15) & 0x1FFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FF) << (13 - 9);
  out++;
  *out = (inl >> 9) & 0x1FFF;
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7) << (13 - 3);
  out++;
  *out = (inl >> 3) & 0x1FFF;
  out++;
  *out = (inl >> 16) & 0x1FFF;
  out++;
  *out = (inl >> 29);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (13 - 10);
  out++;
  *out = (inl >> 10) & 0x1FFF;
  out++;
  *out = (inl >> 23);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (13 - 4);
  out++;
  *out = (inl >> 4) & 0x1FFF;
  out++;
  *out = (inl >> 17) & 0x1FFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FF) << (13 - 11);
  out++;
  *out = (inl >> 11) & 0x1FFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1F) << (13 - 5);
  out++;
  *out = (inl >> 5) & 0x1FFF;
  out++;
  *out = (inl >> 18) & 0x1FFF;
  out++;
  *out = (inl >> 31);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (13 - 12);
  out++;
  *out = (inl >> 12) & 0x1FFF;
  out++;
  *out = (inl >> 25);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (13 - 6);
  out++;
  *out = (inl >> 6) & 0x1FFF;
  out++;
  *out = (inl >> 19);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack14_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x3FFF;
  out++;
  *out = (inl >> 14) & 0x3FFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (14 - 10);
  out++;
  *out = (inl >> 10) & 0x3FFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (14 - 6);
  out++;
  *out = (inl >> 6) & 0x3FFF;
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (14 - 2);
  out++;
  *out = (inl >> 2) & 0x3FFF;
  out++;
  *out = (inl >> 16) & 0x3FFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (14 - 12);
  out++;
  *out = (inl >> 12) & 0x3FFF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (14 - 8);
  out++;
  *out = (inl >> 8) & 0x3FFF;
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (14 - 4);
  out++;
  *out = (inl >> 4) & 0x3FFF;
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0x3FFF;
  out++;
  *out = (inl >> 14) & 0x3FFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (14 - 10);
  out++;
  *out = (inl >> 10) & 0x3FFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (14 - 6);
  out++;
  *out = (inl >> 6) & 0x3FFF;
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (14 - 2);
  out++;
  *out = (inl >> 2) & 0x3FFF;
  out++;
  *out = (inl >> 16) & 0x3FFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (14 - 12);
  out++;
  *out = (inl >> 12) & 0x3FFF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (14 - 8);
  out++;
  *out = (inl >> 8) & 0x3FFF;
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (14 - 4);
  out++;
  *out = (inl >> 4) & 0x3FFF;
  out++;
  *out = (inl >> 18);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack15_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x7FFF;
  out++;
  *out = (inl >> 15) & 0x7FFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFF) << (15 - 13);
  out++;
  *out = (inl >> 13) & 0x7FFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FF) << (15 - 11);
  out++;
  *out = (inl >> 11) & 0x7FFF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FF) << (15 - 9);
  out++;
  *out = (inl >> 9) & 0x7FFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7F) << (15 - 7);
  out++;
  *out = (inl >> 7) & 0x7FFF;
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1F) << (15 - 5);
  out++;
  *out = (inl >> 5) & 0x7FFF;
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7) << (15 - 3);
  out++;
  *out = (inl >> 3) & 0x7FFF;
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl % (1U << 1)) << (15 - 1);
  out++;
  *out = (inl >> 1) & 0x7FFF;
  out++;
  *out = (inl >> 16) & 0x7FFF;
  out++;
  *out = (inl >> 31);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (15 - 14);
  out++;
  *out = (inl >> 14) & 0x7FFF;
  out++;
  *out = (inl >> 29);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (15 - 12);
  out++;
  *out = (inl >> 12) & 0x7FFF;
  out++;
  *out = (inl >> 27);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (15 - 10);
  out++;
  *out = (inl >> 10) & 0x7FFF;
  out++;
  *out = (inl >> 25);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (15 - 8);
  out++;
  *out = (inl >> 8) & 0x7FFF;
  out++;
  *out = (inl >> 23);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (15 - 6);
  out++;
  *out = (inl >> 6) & 0x7FFF;
  out++;
  *out = (inl >> 21);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (15 - 4);
  out++;
  *out = (inl >> 4) & 0x7FFF;
  out++;
  *out = (inl >> 19);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (15 - 2);
  out++;
  *out = (inl >> 2) & 0x7FFF;
  out++;
  *out = (inl >> 17);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack16_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0xFFFF;
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFF;
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFF;
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFF;
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFF;
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFF;
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFF;
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFF;
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFF;
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFF;
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFF;
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFF;
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFF;
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFF;
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFF;
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFF;
  out++;
  *out = (inl >> 16);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack17_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x1FFFF;
  out++;
  *out = (inl >> 17);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (17 - 2);
  out++;
  *out = (inl >> 2) & 0x1FFFF;
  out++;
  *out = (inl >> 19);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (17 - 4);
  out++;
  *out = (inl >> 4) & 0x1FFFF;
  out++;
  *out = (inl >> 21);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (17 - 6);
  out++;
  *out = (inl >> 6) & 0x1FFFF;
  out++;
  *out = (inl >> 23);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (17 - 8);
  out++;
  *out = (inl >> 8) & 0x1FFFF;
  out++;
  *out = (inl >> 25);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (17 - 10);
  out++;
  *out = (inl >> 10) & 0x1FFFF;
  out++;
  *out = (inl >> 27);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (17 - 12);
  out++;
  *out = (inl >> 12) & 0x1FFFF;
  out++;
  *out = (inl >> 29);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (17 - 14);
  out++;
  *out = (inl >> 14) & 0x1FFFF;
  out++;
  *out = (inl >> 31);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (17 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl % (1U << 1)) << (17 - 1);
  out++;
  *out = (inl >> 1) & 0x1FFFF;
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7) << (17 - 3);
  out++;
  *out = (inl >> 3) & 0x1FFFF;
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1F) << (17 - 5);
  out++;
  *out = (inl >> 5) & 0x1FFFF;
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7F) << (17 - 7);
  out++;
  *out = (inl >> 7) & 0x1FFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FF) << (17 - 9);
  out++;
  *out = (inl >> 9) & 0x1FFFF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FF) << (17 - 11);
  out++;
  *out = (inl >> 11) & 0x1FFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFF) << (17 - 13);
  out++;
  *out = (inl >> 13) & 0x1FFFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFF) << (17 - 15);
  out++;
  *out = (inl >> 15);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack18_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x3FFFF;
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (18 - 4);
  out++;
  *out = (inl >> 4) & 0x3FFFF;
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (18 - 8);
  out++;
  *out = (inl >> 8) & 0x3FFFF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (18 - 12);
  out++;
  *out = (inl >> 12) & 0x3FFFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (18 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (18 - 2);
  out++;
  *out = (inl >> 2) & 0x3FFFF;
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (18 - 6);
  out++;
  *out = (inl >> 6) & 0x3FFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (18 - 10);
  out++;
  *out = (inl >> 10) & 0x3FFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (18 - 14);
  out++;
  *out = (inl >> 14);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0x3FFFF;
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (18 - 4);
  out++;
  *out = (inl >> 4) & 0x3FFFF;
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (18 - 8);
  out++;
  *out = (inl >> 8) & 0x3FFFF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (18 - 12);
  out++;
  *out = (inl >> 12) & 0x3FFFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (18 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (18 - 2);
  out++;
  *out = (inl >> 2) & 0x3FFFF;
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (18 - 6);
  out++;
  *out = (inl >> 6) & 0x3FFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (18 - 10);
  out++;
  *out = (inl >> 10) & 0x3FFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (18 - 14);
  out++;
  *out = (inl >> 14);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack19_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x7FFFF;
  out++;
  *out = (inl >> 19);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (19 - 6);
  out++;
  *out = (inl >> 6) & 0x7FFFF;
  out++;
  *out = (inl >> 25);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (19 - 12);
  out++;
  *out = (inl >> 12) & 0x7FFFF;
  out++;
  *out = (inl >> 31);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFF) << (19 - 18);
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1F) << (19 - 5);
  out++;
  *out = (inl >> 5) & 0x7FFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FF) << (19 - 11);
  out++;
  *out = (inl >> 11) & 0x7FFFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFFF) << (19 - 17);
  out++;
  *out = (inl >> 17);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (19 - 4);
  out++;
  *out = (inl >> 4) & 0x7FFFF;
  out++;
  *out = (inl >> 23);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (19 - 10);
  out++;
  *out = (inl >> 10) & 0x7FFFF;
  out++;
  *out = (inl >> 29);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (19 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7) << (19 - 3);
  out++;
  *out = (inl >> 3) & 0x7FFFF;
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FF) << (19 - 9);
  out++;
  *out = (inl >> 9) & 0x7FFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFF) << (19 - 15);
  out++;
  *out = (inl >> 15);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (19 - 2);
  out++;
  *out = (inl >> 2) & 0x7FFFF;
  out++;
  *out = (inl >> 21);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (19 - 8);
  out++;
  *out = (inl >> 8) & 0x7FFFF;
  out++;
  *out = (inl >> 27);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (19 - 14);
  out++;
  *out = (inl >> 14);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl % (1U << 1)) << (19 - 1);
  out++;
  *out = (inl >> 1) & 0x7FFFF;
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7F) << (19 - 7);
  out++;
  *out = (inl >> 7) & 0x7FFFF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFF) << (19 - 13);
  out++;
  *out = (inl >> 13);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack20_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0xFFFFF;
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (20 - 8);
  out++;
  *out = (inl >> 8) & 0xFFFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (20 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (20 - 4);
  out++;
  *out = (inl >> 4) & 0xFFFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (20 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFFF;
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (20 - 8);
  out++;
  *out = (inl >> 8) & 0xFFFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (20 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (20 - 4);
  out++;
  *out = (inl >> 4) & 0xFFFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (20 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFFF;
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (20 - 8);
  out++;
  *out = (inl >> 8) & 0xFFFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (20 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (20 - 4);
  out++;
  *out = (inl >> 4) & 0xFFFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (20 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFFF;
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (20 - 8);
  out++;
  *out = (inl >> 8) & 0xFFFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (20 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (20 - 4);
  out++;
  *out = (inl >> 4) & 0xFFFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (20 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack21_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x1FFFFF;
  out++;
  *out = (inl >> 21);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (21 - 10);
  out++;
  *out = (inl >> 10) & 0x1FFFFF;
  out++;
  *out = (inl >> 31);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFF) << (21 - 20);
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FF) << (21 - 9);
  out++;
  *out = (inl >> 9) & 0x1FFFFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFFF) << (21 - 19);
  out++;
  *out = (inl >> 19);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (21 - 8);
  out++;
  *out = (inl >> 8) & 0x1FFFFF;
  out++;
  *out = (inl >> 29);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFF) << (21 - 18);
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7F) << (21 - 7);
  out++;
  *out = (inl >> 7) & 0x1FFFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFFF) << (21 - 17);
  out++;
  *out = (inl >> 17);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (21 - 6);
  out++;
  *out = (inl >> 6) & 0x1FFFFF;
  out++;
  *out = (inl >> 27);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (21 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1F) << (21 - 5);
  out++;
  *out = (inl >> 5) & 0x1FFFFF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFF) << (21 - 15);
  out++;
  *out = (inl >> 15);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (21 - 4);
  out++;
  *out = (inl >> 4) & 0x1FFFFF;
  out++;
  *out = (inl >> 25);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (21 - 14);
  out++;
  *out = (inl >> 14);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7) << (21 - 3);
  out++;
  *out = (inl >> 3) & 0x1FFFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFF) << (21 - 13);
  out++;
  *out = (inl >> 13);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (21 - 2);
  out++;
  *out = (inl >> 2) & 0x1FFFFF;
  out++;
  *out = (inl >> 23);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (21 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl % (1U << 1)) << (21 - 1);
  out++;
  *out = (inl >> 1) & 0x1FFFFF;
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FF) << (21 - 11);
  out++;
  *out = (inl >> 11);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack22_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x3FFFFF;
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (22 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (22 - 2);
  out++;
  *out = (inl >> 2) & 0x3FFFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (22 - 14);
  out++;
  *out = (inl >> 14);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (22 - 4);
  out++;
  *out = (inl >> 4) & 0x3FFFFF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (22 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (22 - 6);
  out++;
  *out = (inl >> 6) & 0x3FFFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFF) << (22 - 18);
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (22 - 8);
  out++;
  *out = (inl >> 8) & 0x3FFFFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFF) << (22 - 20);
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (22 - 10);
  out++;
  *out = (inl >> 10);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0x3FFFFF;
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (22 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (22 - 2);
  out++;
  *out = (inl >> 2) & 0x3FFFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (22 - 14);
  out++;
  *out = (inl >> 14);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (22 - 4);
  out++;
  *out = (inl >> 4) & 0x3FFFFF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (22 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (22 - 6);
  out++;
  *out = (inl >> 6) & 0x3FFFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFF) << (22 - 18);
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (22 - 8);
  out++;
  *out = (inl >> 8) & 0x3FFFFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFF) << (22 - 20);
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (22 - 10);
  out++;
  *out = (inl >> 10);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack23_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x7FFFFF;
  out++;
  *out = (inl >> 23);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (23 - 14);
  out++;
  *out = (inl >> 14);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1F) << (23 - 5);
  out++;
  *out = (inl >> 5) & 0x7FFFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFFF) << (23 - 19);
  out++;
  *out = (inl >> 19);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (23 - 10);
  out++;
  *out = (inl >> 10);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl % (1U << 1)) << (23 - 1);
  out++;
  *out = (inl >> 1) & 0x7FFFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFF) << (23 - 15);
  out++;
  *out = (inl >> 15);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (23 - 6);
  out++;
  *out = (inl >> 6) & 0x7FFFFF;
  out++;
  *out = (inl >> 29);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFF) << (23 - 20);
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FF) << (23 - 11);
  out++;
  *out = (inl >> 11);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (23 - 2);
  out++;
  *out = (inl >> 2) & 0x7FFFFF;
  out++;
  *out = (inl >> 25);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (23 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7F) << (23 - 7);
  out++;
  *out = (inl >> 7) & 0x7FFFFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFFFF) << (23 - 21);
  out++;
  *out = (inl >> 21);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (23 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7) << (23 - 3);
  out++;
  *out = (inl >> 3) & 0x7FFFFF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFFF) << (23 - 17);
  out++;
  *out = (inl >> 17);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (23 - 8);
  out++;
  *out = (inl >> 8) & 0x7FFFFF;
  out++;
  *out = (inl >> 31);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFFF) << (23 - 22);
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFF) << (23 - 13);
  out++;
  *out = (inl >> 13);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (23 - 4);
  out++;
  *out = (inl >> 4) & 0x7FFFFF;
  out++;
  *out = (inl >> 27);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFF) << (23 - 18);
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FF) << (23 - 9);
  out++;
  *out = (inl >> 9);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack24_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0xFFFFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (24 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (24 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (24 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (24 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (24 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (24 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (24 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (24 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (24 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (24 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (24 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (24 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (24 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (24 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFFFF;
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (24 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (24 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack25_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x1FFFFFF;
  out++;
  *out = (inl >> 25);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFF) << (25 - 18);
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FF) << (25 - 11);
  out++;
  *out = (inl >> 11);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (25 - 4);
  out++;
  *out = (inl >> 4) & 0x1FFFFFF;
  out++;
  *out = (inl >> 29);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFFF) << (25 - 22);
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFF) << (25 - 15);
  out++;
  *out = (inl >> 15);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (25 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl % (1U << 1)) << (25 - 1);
  out++;
  *out = (inl >> 1) & 0x1FFFFFF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFFF) << (25 - 19);
  out++;
  *out = (inl >> 19);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (25 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1F) << (25 - 5);
  out++;
  *out = (inl >> 5) & 0x1FFFFFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFFFF) << (25 - 23);
  out++;
  *out = (inl >> 23);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (25 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FF) << (25 - 9);
  out++;
  *out = (inl >> 9);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (25 - 2);
  out++;
  *out = (inl >> 2) & 0x1FFFFFF;
  out++;
  *out = (inl >> 27);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFF) << (25 - 20);
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFF) << (25 - 13);
  out++;
  *out = (inl >> 13);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (25 - 6);
  out++;
  *out = (inl >> 6) & 0x1FFFFFF;
  out++;
  *out = (inl >> 31);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFFF) << (25 - 24);
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFFF) << (25 - 17);
  out++;
  *out = (inl >> 17);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (25 - 10);
  out++;
  *out = (inl >> 10);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7) << (25 - 3);
  out++;
  *out = (inl >> 3) & 0x1FFFFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFFFF) << (25 - 21);
  out++;
  *out = (inl >> 21);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (25 - 14);
  out++;
  *out = (inl >> 14);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7F) << (25 - 7);
  out++;
  *out = (inl >> 7);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack26_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x3FFFFFF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFF) << (26 - 20);
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (26 - 14);
  out++;
  *out = (inl >> 14);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (26 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (26 - 2);
  out++;
  *out = (inl >> 2) & 0x3FFFFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFFF) << (26 - 22);
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (26 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (26 - 10);
  out++;
  *out = (inl >> 10);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (26 - 4);
  out++;
  *out = (inl >> 4) & 0x3FFFFFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFFF) << (26 - 24);
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFF) << (26 - 18);
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (26 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (26 - 6);
  out++;
  *out = (inl >> 6);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0x3FFFFFF;
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFF) << (26 - 20);
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (26 - 14);
  out++;
  *out = (inl >> 14);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (26 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (26 - 2);
  out++;
  *out = (inl >> 2) & 0x3FFFFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFFF) << (26 - 22);
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (26 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (26 - 10);
  out++;
  *out = (inl >> 10);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (26 - 4);
  out++;
  *out = (inl >> 4) & 0x3FFFFFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFFF) << (26 - 24);
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFF) << (26 - 18);
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (26 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (26 - 6);
  out++;
  *out = (inl >> 6);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack27_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x7FFFFFF;
  out++;
  *out = (inl >> 27);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFFF) << (27 - 22);
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFFF) << (27 - 17);
  out++;
  *out = (inl >> 17);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (27 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7F) << (27 - 7);
  out++;
  *out = (inl >> 7);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (27 - 2);
  out++;
  *out = (inl >> 2) & 0x7FFFFFF;
  out++;
  *out = (inl >> 29);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFFF) << (27 - 24);
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFFF) << (27 - 19);
  out++;
  *out = (inl >> 19);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (27 - 14);
  out++;
  *out = (inl >> 14);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FF) << (27 - 9);
  out++;
  *out = (inl >> 9);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (27 - 4);
  out++;
  *out = (inl >> 4) & 0x7FFFFFF;
  out++;
  *out = (inl >> 31);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFFFF) << (27 - 26);
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFFFF) << (27 - 21);
  out++;
  *out = (inl >> 21);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (27 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FF) << (27 - 11);
  out++;
  *out = (inl >> 11);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (27 - 6);
  out++;
  *out = (inl >> 6);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl % (1U << 1)) << (27 - 1);
  out++;
  *out = (inl >> 1) & 0x7FFFFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFFFF) << (27 - 23);
  out++;
  *out = (inl >> 23);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFF) << (27 - 18);
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFF) << (27 - 13);
  out++;
  *out = (inl >> 13);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (27 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7) << (27 - 3);
  out++;
  *out = (inl >> 3) & 0x7FFFFFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFFFFF) << (27 - 25);
  out++;
  *out = (inl >> 25);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFF) << (27 - 20);
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFF) << (27 - 15);
  out++;
  *out = (inl >> 15);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (27 - 10);
  out++;
  *out = (inl >> 10);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1F) << (27 - 5);
  out++;
  *out = (inl >> 5);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack28_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0xFFFFFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFFF) << (28 - 24);
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFF) << (28 - 20);
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (28 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (28 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (28 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (28 - 4);
  out++;
  *out = (inl >> 4);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFFFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFFF) << (28 - 24);
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFF) << (28 - 20);
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (28 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (28 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (28 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (28 - 4);
  out++;
  *out = (inl >> 4);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFFFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFFF) << (28 - 24);
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFF) << (28 - 20);
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (28 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (28 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (28 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (28 - 4);
  out++;
  *out = (inl >> 4);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0xFFFFFFF;
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFFF) << (28 - 24);
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFF) << (28 - 20);
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (28 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (28 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (28 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (28 - 4);
  out++;
  *out = (inl >> 4);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack29_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x1FFFFFFF;
  out++;
  *out = (inl >> 29);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFFFF) << (29 - 26);
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFFFF) << (29 - 23);
  out++;
  *out = (inl >> 23);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFF) << (29 - 20);
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFFF) << (29 - 17);
  out++;
  *out = (inl >> 17);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (29 - 14);
  out++;
  *out = (inl >> 14);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FF) << (29 - 11);
  out++;
  *out = (inl >> 11);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (29 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1F) << (29 - 5);
  out++;
  *out = (inl >> 5);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (29 - 2);
  out++;
  *out = (inl >> 2) & 0x1FFFFFFF;
  out++;
  *out = (inl >> 31);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFFFF) << (29 - 28);
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFFFFF) << (29 - 25);
  out++;
  *out = (inl >> 25);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFFF) << (29 - 22);
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFFF) << (29 - 19);
  out++;
  *out = (inl >> 19);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (29 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFF) << (29 - 13);
  out++;
  *out = (inl >> 13);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (29 - 10);
  out++;
  *out = (inl >> 10);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7F) << (29 - 7);
  out++;
  *out = (inl >> 7);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (29 - 4);
  out++;
  *out = (inl >> 4);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl % (1U << 1)) << (29 - 1);
  out++;
  *out = (inl >> 1) & 0x1FFFFFFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFFFFF) << (29 - 27);
  out++;
  *out = (inl >> 27);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFFF) << (29 - 24);
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFFFF) << (29 - 21);
  out++;
  *out = (inl >> 21);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFF) << (29 - 18);
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFF) << (29 - 15);
  out++;
  *out = (inl >> 15);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (29 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FF) << (29 - 9);
  out++;
  *out = (inl >> 9);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (29 - 6);
  out++;
  *out = (inl >> 6);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7) << (29 - 3);
  out++;
  *out = (inl >> 3);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack30_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x3FFFFFFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFFFF) << (30 - 28);
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFFFF) << (30 - 26);
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFFF) << (30 - 24);
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFFF) << (30 - 22);
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFF) << (30 - 20);
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFF) << (30 - 18);
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (30 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (30 - 14);
  out++;
  *out = (inl >> 14);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (30 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (30 - 10);
  out++;
  *out = (inl >> 10);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (30 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (30 - 6);
  out++;
  *out = (inl >> 6);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (30 - 4);
  out++;
  *out = (inl >> 4);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (30 - 2);
  out++;
  *out = (inl >> 2);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0) & 0x3FFFFFFF;
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFFFF) << (30 - 28);
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFFFF) << (30 - 26);
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFFF) << (30 - 24);
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFFF) << (30 - 22);
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFF) << (30 - 20);
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFF) << (30 - 18);
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (30 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (30 - 14);
  out++;
  *out = (inl >> 14);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (30 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (30 - 10);
  out++;
  *out = (inl >> 10);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (30 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (30 - 6);
  out++;
  *out = (inl >> 6);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (30 - 4);
  out++;
  *out = (inl >> 4);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (30 - 2);
  out++;
  *out = (inl >> 2);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack31_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0) & 0x7FFFFFFF;
  out++;
  *out = (inl >> 31);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFFFFF) << (31 - 30);
  out++;
  *out = (inl >> 30);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFFFFFF) << (31 - 29);
  out++;
  *out = (inl >> 29);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFFFF) << (31 - 28);
  out++;
  *out = (inl >> 28);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFFFFF) << (31 - 27);
  out++;
  *out = (inl >> 27);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFFFF) << (31 - 26);
  out++;
  *out = (inl >> 26);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFFFFF) << (31 - 25);
  out++;
  *out = (inl >> 25);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFFF) << (31 - 24);
  out++;
  *out = (inl >> 24);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFFFF) << (31 - 23);
  out++;
  *out = (inl >> 23);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFFF) << (31 - 22);
  out++;
  *out = (inl >> 22);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFFFF) << (31 - 21);
  out++;
  *out = (inl >> 21);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFFF) << (31 - 20);
  out++;
  *out = (inl >> 20);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFFF) << (31 - 19);
  out++;
  *out = (inl >> 19);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFFF) << (31 - 18);
  out++;
  *out = (inl >> 18);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFFF) << (31 - 17);
  out++;
  *out = (inl >> 17);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFFF) << (31 - 16);
  out++;
  *out = (inl >> 16);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FFF) << (31 - 15);
  out++;
  *out = (inl >> 15);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FFF) << (31 - 14);
  out++;
  *out = (inl >> 14);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FFF) << (31 - 13);
  out++;
  *out = (inl >> 13);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFFF) << (31 - 12);
  out++;
  *out = (inl >> 12);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7FF) << (31 - 11);
  out++;
  *out = (inl >> 11);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3FF) << (31 - 10);
  out++;
  *out = (inl >> 10);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1FF) << (31 - 9);
  out++;
  *out = (inl >> 9);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xFF) << (31 - 8);
  out++;
  *out = (inl >> 8);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7F) << (31 - 7);
  out++;
  *out = (inl >> 7);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3F) << (31 - 6);
  out++;
  *out = (inl >> 6);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x1F) << (31 - 5);
  out++;
  *out = (inl >> 5);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0xF) << (31 - 4);
  out++;
  *out = (inl >> 4);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x7) << (31 - 3);
  out++;
  *out = (inl >> 3);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl & 0x3) << (31 - 2);
  out++;
  *out = (inl >> 2);
  ++in;
  inl = util::SafeLoad(in);
  *out |= (inl % (1U << 1)) << (31 - 1);
  out++;
  *out = (inl >> 1);
  ++in;
  out++;

  return in;
}

inline const uint32_t* unpack32_32(const uint32_t* in, uint32_t* out) {
  uint32_t inl = util::SafeLoad(in);
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  inl = util::SafeLoad(in);
  out++;
  *out = (inl >> 0);
  ++in;
  out++;

  return in;
}

inline const uint32_t* nullunpacker32(const uint32_t* in, uint32_t* out) {
  for (int k = 0; k < 32; ++k) {
    out[k] = 0;
  }
  return in;
}

inline int unpack32(const uint32_t* in, uint32_t* out, int batch_size, int num_bits) {
  batch_size = batch_size / 32 * 32;
  int num_loops = batch_size / 32;

  switch (num_bits) {
    case 0:
      for (int i = 0; i < num_loops; ++i) in = nullunpacker32(in, out + i * 32);
      break;
    case 1:
      for (int i = 0; i < num_loops; ++i) in = unpack1_32(in, out + i * 32);
      break;
    case 2:
      for (int i = 0; i < num_loops; ++i) in = unpack2_32(in, out + i * 32);
      break;
    case 3:
      for (int i = 0; i < num_loops; ++i) in = unpack3_32(in, out + i * 32);
      break;
    case 4:
      for (int i = 0; i < num_loops; ++i) in = unpack4_32(in, out + i * 32);
      break;
    case 5:
      for (int i = 0; i < num_loops; ++i) in = unpack5_32(in, out + i * 32);
      break;
    case 6:
      for (int i = 0; i < num_loops; ++i) in = unpack6_32(in, out + i * 32);
      break;
    case 7:
      for (int i = 0; i < num_loops; ++i) in = unpack7_32(in, out + i * 32);
      break;
    case 8:
      for (int i = 0; i < num_loops; ++i) in = unpack8_32(in, out + i * 32);
      break;
    case 9:
      for (int i = 0; i < num_loops; ++i) in = unpack9_32(in, out + i * 32);
      break;
    case 10:
      for (int i = 0; i < num_loops; ++i) in = unpack10_32(in, out + i * 32);
      break;
    case 11:
      for (int i = 0; i < num_loops; ++i) in = unpack11_32(in, out + i * 32);
      break;
    case 12:
      for (int i = 0; i < num_loops; ++i) in = unpack12_32(in, out + i * 32);
      break;
    case 13:
      for (int i = 0; i < num_loops; ++i) in = unpack13_32(in, out + i * 32);
      break;
    case 14:
      for (int i = 0; i < num_loops; ++i) in = unpack14_32(in, out + i * 32);
      break;
    case 15:
      for (int i = 0; i < num_loops; ++i) in = unpack15_32(in, out + i * 32);
      break;
    case 16:
      for (int i = 0; i < num_loops; ++i) in = unpack16_32(in, out + i * 32);
      break;
    case 17:
      for (int i = 0; i < num_loops; ++i) in = unpack17_32(in, out + i * 32);
      break;
    case 18:
      for (int i = 0; i < num_loops; ++i) in = unpack18_32(in, out + i * 32);
      break;
    case 19:
      for (int i = 0; i < num_loops; ++i) in = unpack19_32(in, out + i * 32);
      break;
    case 20:
      for (int i = 0; i < num_loops; ++i) in = unpack20_32(in, out + i * 32);
      break;
    case 21:
      for (int i = 0; i < num_loops; ++i) in = unpack21_32(in, out + i * 32);
      break;
    case 22:
      for (int i = 0; i < num_loops; ++i) in = unpack22_32(in, out + i * 32);
      break;
    case 23:
      for (int i = 0; i < num_loops; ++i) in = unpack23_32(in, out + i * 32);
      break;
    case 24:
      for (int i = 0; i < num_loops; ++i) in = unpack24_32(in, out + i * 32);
      break;
    case 25:
      for (int i = 0; i < num_loops; ++i) in = unpack25_32(in, out + i * 32);
      break;
    case 26:
      for (int i = 0; i < num_loops; ++i) in = unpack26_32(in, out + i * 32);
      break;
    case 27:
      for (int i = 0; i < num_loops; ++i) in = unpack27_32(in, out + i * 32);
      break;
    case 28:
      for (int i = 0; i < num_loops; ++i) in = unpack28_32(in, out + i * 32);
      break;
    case 29:
      for (int i = 0; i < num_loops; ++i) in = unpack29_32(in, out + i * 32);
      break;
    case 30:
      for (int i = 0; i < num_loops; ++i) in = unpack30_32(in, out + i * 32);
      break;
    case 31:
      for (int i = 0; i < num_loops; ++i) in = unpack31_32(in, out + i * 32);
      break;
    case 32:
      for (int i = 0; i < num_loops; ++i) in = unpack32_32(in, out + i * 32);
      break;
    default:
      assert(false && "Unsupported num_bits");
  }

  return batch_size;
}

}  // namespace internal
}  // namespace parquet4seastar
