name: CMake on a single platform

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: stdbio/fedora:39-1

    steps:
      - uses: actions/checkout@v3

      - name: Get Seastar
        run: git clone https://github.com/scylladb/seastar.git

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSEASTAR_PATH=${{github.workspace}}/seastar  -DENABLE_PARQUET4SEASTAR_TEST=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        run: |
          build/tests/byte_stream_split_test          
          build/tests/compression_test
          build/tests/cql_reader_test
          build/tests/delta_binary_packed_test
          build/tests/delta_length_byte_array_test
          build/tests/file_writer_test
          build/tests/rle_encoding_test
          build/tests/thrift_serdes_test_test
          build/tests/column_chunk_writer_test
          build/tests/cql_reader_alltypes_test
          build/tests/delta_byte_array_test
          build/tests/dictionary_encoder_test

